name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # 3️⃣ Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4️⃣ Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 5️⃣ Create google-services.json
      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json

      # 6️⃣ Make Gradle executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 7️⃣ Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 8️⃣ Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      # 9️⃣ Run Instrumentation Tests (emulator)
      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          target: google_apis
          script: ./gradlew connectedDebugAndroidTest --stacktrace

      # 🔟 Upload Debug APK as Artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
